apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secret
type: Opaque
data:
  MONGO_URL: bW9uZ29kYjovL21vbmdvOjI3MDE3
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
  JWT_SECRET: c3BvcnRzX2h1Yl9qd3Rfc2VjcmV0XzQ1Ng==
